language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - ruby-head
  - ree
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree
notifications:
  recipients:
    - alexrabarts@gmail.com
